version: '3.1'

services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    volumes:
      - ./ghost-content:/var/lib/ghost/content
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ghost
    volumes:
      - ./ghost-db:/var/lib/mysql